-- Business Setup Settings
INSERT IGNORE INTO system_settings (setting_key, setting_value, is_active) VALUES
('maintenance_mode', '0', 0),
('company_name', '', 1),
('company_email', '', 1),
('company_phone', '', 1),
('company_country', 'India', 1),
('company_description', '', 1),
('company_latitude', '', 1),
('company_longitude', '', 1),
('company_logo', '', 1),
('company_favicon', '', 1),
('time_zone', 'Asia/Kolkata', 1),
('time_format', '12', 1),
('country_picker_status', '1', 1),
('currency_code', 'INR', 1),
('currency_symbol_position', 'left', 1),
('decimal_digits', '0', 1),
('business_model', 'commission', 1),
('default_commission', '12', 1),
('commission_on_delivery', '0', 1),
('additional_charge_status', '0', 0),
('additional_charge_name', 'Packing Charges', 1),
('additional_charge_amount', '10', 1),
('copyright_text', '', 1),
('cookies_text', 'Cookies', 1);
